Early-out for gitfr

diff --git a/bin/gitfr b/bin/gitfr
--- a/bin/gitfr
+++ b/bin/gitfr
@@ -1,5 +1,22 @@
-set -x
+require_clean_work_tree () {
+  # Update the index
+  git update-index -q --ignore-submodules --refresh
+
+  # Disallow unstaged changes in the working tree
+  if ! git diff-files --quiet --ignore-submodules --
+  then
+    echo >&2 "cannot rebase: you have unstaged changes."
+    git diff-files --name-status -r --ignore-submodules -- >&2
+    exit 1
+  fi
+}
+
+# see upfront if we will be able to rebase after the fetch so that I notice
+# while still at the console
+require_clean_work_tree
+
 git fetch
 if [ $? -eq 0 ]; then
    git rebase
 fi
+
